input_schema = {
  "type": "object",
  "properties": {
    "V1": { "type": "array", "items": { "type": "number" } },
    "V2": { "type": "array", "items": { "type": "number" } },
    "V3": { "type": "array", "items": { "type": "number" } },
    "V4": { "type": "array", "items": { "type": "number" } },
    "V5": { "type": "array", "items": { "type": "number" } },
    "V6": { "type": "array", "items": { "type": "number" } },
    "V7": { "type": "array", "items": { "type": "number" } },
    "V8": { "type": "array", "items": { "type": "number" } },
    "V9": { "type": "array", "items": { "type": "number" } },
    "V10": { "type": "array", "items": { "type": "number" } },
    "V11": { "type": "array", "items": { "type": "number" } },
    "V12": { "type": "array", "items": { "type": "number" } },
    "V13": { "type": "array", "items": { "type": "number" } },
    "V14": { "type": "array", "items": { "type": "number" } },
    "V15": { "type": "array", "items": { "type": "number" } },
    "V16": { "type": "array", "items": { "type": "number" } },
    "V17": { "type": "array", "items": { "type": "number" } },
    "V18": { "type": "array", "items": { "type": "number" } },
    "V19": { "type": "array", "items": { "type": "number" } },
    "V20": { "type": "array", "items": { "type": "number" } },
    "V21": { "type": "array", "items": { "type": "number" } },
    "V22": { "type": "array", "items": { "type": "number" } },
    "V23": { "type": "array", "items": { "type": "number" } },
    "V24": { "type": "array", "items": { "type": "number" } },
    "V25": { "type": "array", "items": { "type": "number" } },
    "V26": { "type": "array", "items": { "type": "number" } },
    "V27": { "type": "array", "items": { "type": "number" } },
    "V28": { "type": "array", "items": { "type": "number" } },
    "Time": { "type": "array", "items": { "type": "number" } },
    "Amount": { "type": "array", "items": { "type": "number" } }
  },
  "required": [
    "V1",
    "V2",
    "V3",
    "V4",
    "V5",
    "V6",
    "V7",
    "V8",
    "V9",
    "V10",
    "V11",
    "V12",
    "V13",
    "V14",
    "V15",
    "V16",
    "V17",
    "V18",
    "V19",
    "V20",
    "V21",
    "V22",
    "V23",
    "V24",
    "V25",
    "V26",
    "V27",
    "V28",
    "Amount"
  ]
}
